server:
  port: 17788

spring:
  application:
    name: developer-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      httpclient:
        pool:
          max-idle-time: 10000
          max-connections: 30
  codec:
    max-in-memory-size: 5MB